### ISSUE TITLE
Error en la etiqueta de cierre h1

### ISSUE THREAD

**Issue by JavierPA3** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-victorfernandezesp#1]
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-victorfernandezesp/blob/6618883002311e68e6ac1abc41b67c0b189ce6b7/index.html#L10

El error se soluciona con poner un </h1> en vez de </h>

**Comment by JavierPA3** [comment]
Arreglalo!

**Comment by victorfernandezesp** [comment]
ok

**Comment by victorfernandezesp** [comment]
Hecho.
